### ISSUE TITLE
Feature request - Be able to pull Tasks from 2 or more folder

### ISSUE THREAD

**Issue by MichaelLepori** [obsidianmd/obsidian-sample-plugin#107]
Hi,

first of all, great job and great Idea to create a plugin like this.

A way to select 2 folders instead just one or all would be nice.

Maybe it will possible in the future to select different folders. Who knows? :-D

Thank you.

**Comment by joethei** [comment]
How is this related to the sample plugin?

**Comment by MichaelLepori** [comment]
Hi @joethei!!
I am very sorry. I thought I was on the Plugin: "Task List in Kanban Mode".
My mistake.

Take care.

All the best to you.

Michael
