### ISSUE TITLE
Options - Where is the button?

### ISSUE THREAD

**Issue by MichaelLepori** [obsidianmd/obsidian-sample-plugin#108]
Hi,

after I did the update 1.2.5 I am not able to see the Button for the settings anymore.

![image](https://github.com/user-attachments/assets/6065dd19-0037-4194-86f2-b77e73b48a12)

Thank you!

Mic.

**Comment by joethei** [comment]
This is the repository for the Obsidian Sample plugin, you are looking for this repo: https://github.com/chrskerr/task-list-kanban
