### ISSUE TITLE
Why isn't there a restricted mode for themes?

### ISSUE THREAD

**Issue by alberfantom** [obsidianmd/obsidian-sample-plugin#119]
![Screenshot_20241109-111923.jpg](https://github.com/user-attachments/assets/ef6f6039-2639-4cef-a239-907190cba3d9)

![Screenshot_20241109-111911.jpg](https://github.com/user-attachments/assets/ed42b707-ea3c-4dd1-a7d7-8a0c2c095be7)

**Comment by lishid** [comment]
This is not the right place for questions. Please go to https://forum.obsidian.md/ instead.
