### ISSUE TITLE
es2020 as target/libs in tsconfig.json?

### ISSUE THREAD

**Issue by gavvvr** [obsidianmd/obsidian-sample-plugin#12]
Hi. I wanted to use `Promise.allSettled` in my plugin, but Typescript said:

> Property 'allSettled' does not exist on type 'PromiseConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2020' or later.ts(2550)

Are there any obstacles preventing Obsidian plugins to switch to es2020 from es2015? I think Electron apps like Obsidian use modern Chromium under the hood which should support es2020. Simple test in Obsidian dev console shows me that Obsidian knows about this method:

![image](https://user-images.githubusercontent.com/1719646/122580461-a9405180-d05e-11eb-8197-ba66d80d52ff.png)

**Comment by gavvvr** [comment]
With `navigator.userAgent` I can see the Chrome version of my current Obsidian 0.12.3 is 87.0.4280.88.
[CanIUse](https://caniuse.com/?feats=mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nullish_coalescing,mdn-javascript_builtins_globalthis,es6-module-dynamic-import,bigint,mdn-javascript_builtins_promise_allsettled,mdn-javascript_builtins_string_matchall,mdn-javascript_statements_export_namespace,mdn-javascript_statements_import_meta) tells me all es2020 features are supported, and I guess earlier features are supported too.

**Comment by lishid** [comment]
Plugins don't always run on Electron. If you're ok that your plugin only runs in the desktop app, then targeting ES2020 is fine, but keep in mind that Obsidian will run perfectly fine on some older Android and iOS devices that aren't able to get the latest webview update, but your plugin will not function given its reliance on latest tech.

**Comment by gavvvr** [comment]
Thanks for the explanation @lishid. I completely forgot about the mobile app.

**Comment by texastoland** [comment]
I got this error updating a dependency:

```yaml
warning: "import.meta" is not available in the configured target environment ("es2018") and will be empty
```

[98% of mobile browsers](https://caniuse.com/?search=import.meta) now support it. Time to move the target forward for compatibility with modern packages?
