### ISSUE TITLE
ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by WHG555** [obsidianmd/obsidian-sample-plugin#14]
![QQ截图20210924184052](https://user-images.githubusercontent.com/26180549/134661817-0e791790-8b7d-42e9-850a-4453f288657e.jpg)
我使用了`cmEditor: CodeMirror.Editor;`来进行文件的修改。当文件更改时， 我会更新文件中的一个字段，突然它就出现了这个情况。当前编辑的文档内容都没有了

**Comment by akosbalasko** [comment]
Hi @WHG555 ,
I don't think it's related to the plugin itself, the error reports that you run out of space in your hard drive.
