### ISSUE TITLE
can't use `child_process` or `fs` module?

### ISSUE THREAD

**Issue by egradman** [obsidianmd/obsidian-sample-plugin#18]
I'm building a new plugin that needs to access the filesystem and spawn child processes.  But `npm run dev` throws an error when I import and use either of these modules.

How to replicate:

1. clone this repo
2. add `import { spawn }  from 'child_process';` to `main.ts` (note, that this _alone_ does not cause the issue)
3. add `spawn("something")` to `onload()`
4. `npm run dev`

The error I get is `main.ts:2:29: error: Could not resolve "child_process" (use "platform: 'node'" when building for node)`

Is this related to #11 and the switch to ESBuild instead of Rollup? <-- I don't understand any of this, but I do notice that all the other plugins that use `child_process` and `fs` refer to `rollup` in `package.json` instead of `esbuild`.

**Comment by lishid** [comment]
I will try to figure this out!

**Comment by lishid** [comment]
I have updated the build script to fix this issue.
