### ISSUE TITLE
Fails on iPhone

### ISSUE THREAD

**Issue by bicarlsen** [obsidianmd/obsidian-sample-plugin#21]
When installing the sample plugin on iPhone I receive the error
```
"Plugin failure: obsidian-sample-plugin"
Object {2}
@capacitor://localhost/app.js:1:120182
a@capacitor://localhost/app.js:119073
promiseReactionJob@[native code]
```

I receive a similar error for my plugin [Obsidian Image Caption](https://github.com/bicarlsen/obsidian_image_caption/issues/4) which is why I wanted to try with the basic sample plugin.

I'm running an iPhone 7 with software version 15.1, and Obsidian version 1.0.5.

**Comment by lishid** [comment]
Hmm it seems that the error object isn't properly printed by the console you're using. I've tried Image Caption and the error I'm seeing (with a proper debug mode Safari remote debugger) is:

SyntaxError: Invalid regular expression: invalid group specifier name.

This seems to be due to the use of the negative lookbehind. I will comment on that plugin's issue.

**Comment by bicarlsen** [comment]
Thanks @lishid . Do you know what is causing the error in the smaple plugin on mobile?

**Comment by lishid** [comment]
I did not check actually. What process did you use to build/install the sample plugin? As far as I know it's not available in the plugin store.

**Comment by bicarlsen** [comment]
I cloned the repository to my local machine, then transferred it to my phone via USB.

**Comment by lishid** [comment]
Did you build it and test on desktop first?

**Comment by bicarlsen** [comment]
I had not, and indeed rebuilding the app fixed the issue.
I assumed the included `main.js` would correspond to the build of the code, but perhaps it doesn't?

Thanks for pointing that out.

**Comment by lishid** [comment]
The main.ts file is the typescript source and it's built into main.js which is what Obsidian actually runs on.

**Comment by bicarlsen** [comment]
Ah, sorry. I didn't realize there wasn't a `main.js` file included with the plugin by default. Just an oversight on my side.
