### ISSUE TITLE
the version in `manifest.json` is 1.0.1 but there is no corresponding release

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-sample-plugin#27]
Although it should not affect any real-life usages, maybe it's better to create a 1.0.1 release [here](https://github.com/obsidianmd/obsidian-sample-plugin/releases)?

**Comment by lishid** [comment]
I've done an alternative fix to remove 1.0.1 - better for new plugins to start at 1.0.0 anyway.
