### ISSUE TITLE
Where does console.log() log to?

### ISSUE THREAD

**Issue by trydalch** [obsidianmd/obsidian-sample-plugin#3]
This is probably a really dumb question, but I cannot find where it logs to.

**Comment by Vinzent03** [comment]
Just press `Ctrl` + `Shift` + `i`. A console with all `console.log` will appear.

**Comment by trydalch** [comment]
Like I said, I figured it was a dumb question. Thank you.

**Comment by Vinzent03** [comment]
Maybe ask on the discord next time. I think that's better than an issue.

**Comment by trydalch** [comment]
Good plan. Wasn't aware of the discord server. I'll do that next time for sure.
