### ISSUE TITLE
What updates are needed to reflect the change to codemirror CM 6?

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [obsidianmd/obsidian-sample-plugin#32]
The Obsidian forum has this [guide for plugin developers](https://forum.obsidian.md/t/plugin-developers-codemirror-6-migration-guide-for-v6-0/38947) on the CM 6 / codemirror  v6.0 upgrade in the obsidian API. What changes need to be made to this sample plugin to follow the guide? For example, I think the list in the `esbuild` config needs updating, but are other changes necessary? Thanks in advance for any and all answers or links to further reading!

**Comment by lishid** [comment]
The sample plugin isn't importing any of the CodeMirror packages by default so there isn't much change required here. However, for your plugin that uses CodeMirror 6 packages, you will want to upgrade all of them to `^6.0.0` or later.
