### ISSUE TITLE
remove default CSS rule in boilerplate?

### ISSUE THREAD

**Issue by dpickett** [obsidianmd/obsidian-sample-plugin#35]
hi there,

Would you accept a PR that eliminates the `body` rule in `styles.css`? I wasn't aware it was in there, and I hosed a lot of people's themes when they installed my plugin :-) 

Let me know and I'd be happy to PR it.

**Comment by lishid** [comment]
Hasn't been a problem for about a year and a half, but I guess I can change it.

**Comment by lishid** [comment]
Fixed in 64e86498772c97c6f49fd28698405547fd44dc60
