### ISSUE TITLE
Switch to esbuild 17

### ISSUE THREAD

**Issue by p-l-** [obsidianmd/obsidian-sample-plugin#45]
The provided file `esbuild.config.mjs` is compatible / works well with `esbuild<=16.*` but not with `>=17.*`.

Would it be possible to update it using the new API? Sorry I have been unable to fix the file and create a PR myself, for I'm a total noob!

**Comment by timrogers** [comment]
@p-l- FYI, I have made a PR to fix this in #47. Hopefully it gets merged soon! You can always use my proposed config file yourself if you don't want to wait.
