### ISSUE TITLE
use this template

### ISSUE THREAD

**Issue by 1C0D** [obsidianmd/obsidian-sample-plugin#64]
I don't see it anymore ?
![image](https://github.com/obsidianmd/obsidian-sample-plugin/assets/63018905/16b885d1-923e-4fed-9a12-c5e19b56265d)

**Comment by lishid** [comment]
That's a github UI bug. If you zoom out, or make the window wider it will show up.

**Comment by 1C0D** [comment]
@lishid nice one. They are modifying a lot the UI these days, which is a good thing. If you know how to get rid of this blue dot BTW, I take it
![image](https://github.com/obsidianmd/obsidian-sample-plugin/assets/63018905/e5cb2ed6-fe11-41cd-9a2b-d49aa3f76b54)

**Comment by lishid** [comment]
If you click on it, it disappears.

**Comment by 1C0D** [comment]
no, no way...
