### ISSUE TITLE
Display download successful, but not in the local file library

### ISSUE THREAD

**Issue by 161424** [obsidianmd/obsidian-sample-plugin#85]
![image](https://github.com/obsidianmd/obsidian-sample-plugin/assets/32435360/d274c5dc-5358-40dd-9a35-a98a8a4ef3a9)

The computer version is Win11, and the application version is v1.4.16

**Comment by lishid** [comment]
This is the wrong repo to send this issue. I think you meant to send to a plugin's repo.
